version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.11
      
  build:
    commands:
      - rsync -avz --progress --exclude='.git' --exclude='.gitlab-ci.yml' ./ /home/ubuntu/python
  post_build:
    commands:
      - echo code deployment on ec2 completed
artifacts:
  files:
    - appspec.yml
  discard-paths: yes
