version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.11
             
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - /root/.pyenv/versions/3.11/bin/python3.11 -m pip install --upgrade pip
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 468085339621.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=468085339621.dkr.ecr.ap-south-1.amazonaws.com/ecs-python
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - pip install -r requirements.txt
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"ecs-python","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json #this represent the name of container
artifacts:
    files: imagedefinitions.json
