version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.9
      
  build:
    commands:
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
